version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: oreooks-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: oreooks
      POSTGRES_PASSWORD: oreooks
      POSTGRES_DB: oreooks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/oreooks-bot-db-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  postgres_data:
